apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    name: nginx-app
    env: staging
spec:
  containers:
    - name: nginx-app
      image: nginx
      ports:
        - containerPort: 80
        
