apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    name: nginx-app
    env: staging
spec:
  selector:
    name: nginx-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP