apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ruby-blog
  labels:
    app: ruby-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-blog
  template: 
    metadata: 
      labels:
        app: ruby-blog
    spec:
      containers:
      - name: ruby-blog-container
        image: us.gcr.io/x-oxygen-191506/ruby-blog:v2
        resources:
          requests:
              cpu: 100m
              memory: 100Mi
        ports:
        - containerPort: 80


