apiVersion: v1
kind: Service
metadata:
  name: ruby-blog-app
  labels:
    name: ruby-blog-app
    env: staging
spec:
  selector:
    name: ruby-blog-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP